name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: vintagesucks
          template: classic
          base: header, activity, community
          config_animated: yes
          config_timezone: Europe/Berlin
